spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/api/patient/**
        - id: doctor-service
          uri: lb://doctor-service
          predicates:
            - Path=/api/doctor/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payment/**

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
